Impostor Radio & PushToTalk Compatability
OhMyGuus/BetterCrewLink pull request #322
Opened 2022-07-04 00:52 UTC by JKohlman

I don't actually have the setup to test this at the moment but I believe currently radio & push to talk requires two buttons at once. This should make it so that just holding the radio button works.

2022-07-07 22:32 UTC, OhMyGuus requested changes

2022-07-07 22:32 UTC, OhMyGuus commented on src/main/hook.ts
> +				event.sender.send(IpcRendererMessages.PUSH_TO_TALK, false);
What if the player still has his push to talk button pressed

2022-07-07 22:33 UTC, OhMyGuus commented on src/main/hook.ts
> +				event.sender.send(IpcRendererMessages.PUSH_TO_TALK, false);
Apparently this comment was still on pending thought you where able to see it when it was on pending

2022-07-10 20:15 UTC, JKohlman commented on src/main/hook.ts
> +				event.sender.send(IpcRendererMessages.PUSH_TO_TALK, false);
Should be fixed by latest commit

2022-07-14 20:46 UTC, JKohlman commented
I resolved those changes, not sure why it's still saying changes requested.

2022-07-14 23:23 UTC, merged